name: dashboad
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1

  flutter_svg: ^2.0.10+1

  flutter_screenutil: ^5.9.3

  go_router: ^14.2.0

  animated_text_kit: ^4.2.2
  flutter_styled_toast: ^2.2.1
  animate_do: ^3.3.4

  intl: ^0.19.0

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  mime: ^1.0.5
  pinput: ^5.0.0

  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0

  dio: ^5.5.0+1
  shared_preferences: ^2.2.3

  get_it: ^7.7.0
  dartz: ^0.10.1

  progress_state_button: ^1.0.4
  progress_loading_button: ^2.0.2

  shimmer: ^3.0.0
  file_picker: ^8.0.6
  awesome_dialog: ^3.2.1

  web_socket_channel: ^3.0.1

  conditional_builder_null_safety: ^0.0.6

  lottie: ^3.1.2

  image_network: ^2.5.6

  equatable: ^2.0.5
  open_file: ^3.3.2
  flutter_masonry_view: ^0.0.2
  shaky_animated_listview: ^0.0.5
  flutter_staggered_animations: ^1.1.1
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
